license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="EaseCation"
description='''
Unified EaseCation client settings with pause-menu and keyboard access.
'''

[[mixins]]
config="ecclientsettings.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},20.0.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="netease_bridge_client"
type="required"
versionRange="[1.0.0,)"
ordering="AFTER"
side="CLIENT"

